feat: add an `exitOnEnter` option
sant123/get_stdin pull request #2
Opened 2020-10-07 22:39 UTC by Vehmloewff

Adds an `exitOnEnter` option to all four of the function exported by `mod.ts`.

To preserve backward compatibility, the new `options` parameter is optional, and the default value of `exitOnEnter` is `true`, the previous behavior.

2020-10-07 22:53 UTC, sant123 commented
Could you elaborate an example in the README file under `usage` section? 

I suppose this enhancement is for reading files through stdin. 

So would be good to show an example of the file being `cat` and passed through the `|`. 

```sh
$ cat myfile.txt | deno run --allow-run ./example.ts
unicorns
more unicorns
unicorns unicorns unicorns
```

2020-10-08 00:40 UTC, Vehmloewff commented
Sure thing!

2020-10-08 00:48 UTC, sant123 requested changes

2020-10-08 00:48 UTC, sant123 commented on README.md
> +const input = await getStdin({ exitOnEnter: false })
Please add a semicolon at the end.

2020-10-08 00:48 UTC, sant123 commented on README.md
> +console.log(`Received a bunch of (possibly) multiline text from stdin:\n${input}`)
Please add a semicolon at the end.

2020-10-08 00:55 UTC, sant123 approved these changes
LGTM

2020-10-08 00:56 UTC, sant123 commented
Thanks for the PR @Vehmloewff.

2020-10-08 00:56 UTC, merged

2020-10-08 00:57 UTC, Vehmloewff commented
No problem!

2020-10-08 01:16 UTC, sant123 commented
Published https://deno.land/x/get_stdin@v1.1.0